const course = [
  ['Order with confidence','Restaurant Spanish','At a restaurant'],['Customize an order','Restaurant Spanish','Dietary needs and preferences'],['Pay and say goodbye','Restaurant Spanish','The check, tip, and thanks'],['Find your way around','Transportation','Directions and landmarks'],['Move through the city','Transportation','Taxis, rideshares, buses'],['Tickets and schedules','Transportation','Stations, platforms, and times'],['Week 1 travel mission','Mission','A full day in a new city'],
  ['Check in smoothly','Hotels','Your reservation and room'],['Ask for what you need','Hotels','Breakfast, Wi-Fi, and towels'],['Fix a problem','Hotels','Polite complaints and solutions'],['Numbers that matter','Practical Spanish','Prices, dates, and times'],['Make and change plans','Practical Spanish','Appointments and reservations'],['Listen for the gist','Listening','Natural hotel and street speech'],['Week 2 travel mission','Mission','A two-night hotel stay'],
  ['Introduce yourself','Meeting locals','Who you are and where you live'],['Ask better questions','Meeting locals','Follow-ups that keep a conversation going'],['Talk about your day','Conversation','Present-tense routines'],['Tell a travel story','Conversation','Simple past experiences'],['Share preferences','Conversation','Likes, dislikes, and recommendations'],['Make future plans','Conversation','Near-future plans and invitations'],['Week 3 conversation mission','Mission','Five minutes with a local'],
  ['Get unstuck','Repair strategies','What to say when you miss a word'],['Understand connected speech','Listening','Fast everyday phrases'],['Mexico listening lab','Regional listening','Common Mexican patterns'],['Costa Rica listening lab','Regional listening','Usted, vos, and local rhythm'],['Spain listening lab','Regional listening','Vosotros and regional vocabulary'],['Handle an unexpected change','Problem-solving','Missed trains and changed plans'],['Week 4 travel mission','Mission','A day trip entirely in Spanish'],
  ['Restaurant + transport simulation','Full simulation','Combine skills under time pressure'],['Hotel + locals simulation','Full simulation','Check in, ask advice, socialize'],['Final travel day','Final assessment','Listen, decide, respond, reflect']
];
const scene = [
  {who:'SERVER', es:'Buenas tardes. ¿Qué le gustaría?', en:'Good afternoon. What would you like?'},
  {who:'YOU', es:'Quisiera los tacos al pastor, por favor.', en:"I'd like the tacos al pastor, please."},
  {who:'SERVER', es:'¿Para tomar?', en:'To drink?'},
  {who:'YOU', es:'Agua sin gas, por favor.', en:'Still water, please.'},
  {who:'SERVER', es:'¿Algo más?', en:'Anything else?'},
  {who:'YOU', es:'No, gracias. Eso es todo.', en:"No, thank you. That's all."}
];
const phrases=[['Quisiera...',"I would like..."],['por favor','please'],['Agua sin gas','still water'],['la cuenta','the check']];
let day=Number(localStorage.getItem('viajero-day')||1), completed=Number(localStorage.getItem('viajero-progress')||0), synth=window.speechSynthesis;
const $=s=>document.querySelector(s);
function speak(text){if(!synth)return;synth.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='es-MX';u.rate=.88;synth.speak(u)}
function renderProgress(){ $('#progressText').textContent=`${completed} / 6`;$('#progressBar').style.width=`${Math.min(completed/6*100,100)}%`;localStorage.setItem('viajero-progress',completed);localStorage.setItem('viajero-day',day);$('#streakCount').textContent=localStorage.getItem('viajero-streak')||1 }
function renderDay(){const item=course[day-1];$('#dayEyebrow').textContent=`DAY ${String(day).padStart(2,'0')} · ${item[1].toUpperCase()}`;$('#heroTitle').textContent=item[0]+'.';$('#heroCopy').textContent=day===1?'A 2-hour intensive lesson for the moments that make travel feel easy. Listen, repeat, then take the wheel.':`Today's focus: ${item[2]}. Spend two focused hours listening, speaking, and using the language in context.`;$('#sceneEyebrow').textContent=`DAY ${String(day).padStart(2,'0')} · SCENE`;$('#sceneTitle').textContent=item[2];renderRoadmap()}
function renderScene(){ $('#sceneCard').innerHTML=scene.map(x=>`<div class="line"><span class="speaker">${x.who}</span><span class="spanish">${x.es}</span><span class="english">${x.en}</span><button class="tiny-play" data-say="${x.es.replaceAll('"','&quot;')}" aria-label="Play Spanish">▶</button></div>`).join('');document.querySelectorAll('[data-say]').forEach(b=>b.onclick=()=>speak(b.dataset.say)) }
function renderPhrases(){ $('#phraseGrid').innerHTML=phrases.map(x=>`<div class="phrase"><button data-say="${x[0]}">🔊</button><p>${x[0]}</p><small>${x[1]}</small></div>`).join('');document.querySelectorAll('.phrase [data-say]').forEach(b=>b.onclick=()=>speak(b.dataset.say)) }
function renderChallenge(){const row=$('#choiceRow'),sentence=$('#sentence');let picked=[];const options=['Quisiera','los tacos al pastor','por favor','la cuenta'];function draw(){sentence.innerHTML=picked.map(x=>`<span class="chip">${x}</span>`).join('')||'<span style="color:#9b8176">Tap words to build: “I would like the tacos al pastor, please.”</span>';row.innerHTML=options.filter(x=>!picked.includes(x)).map(x=>`<button class="choice">${x}</button>`).join('');row.querySelectorAll('button').forEach(b=>b.onclick=()=>{picked.push(b.textContent);draw();if(picked.join(' ')==='Quisiera los tacos al pastor'){ $('#challengeFeedback').textContent='Great. Now add por favor for extra politeness.';$('#challengeFeedback').className='feedback try'}if(picked.join(' ')==='Quisiera los tacos al pastor por favor'){ $('#challengeFeedback').textContent='¡Perfecto! You built a natural order.';$('#challengeFeedback').className='feedback good';mark()}})}draw()}
function mark(){if(completed<6){completed++;renderProgress()}}
function renderReview(){ $('#reviewList').innerHTML=[['Buenas tardes','Good afternoon'],['¿Qué le gustaría?','What would you like?'],['Quisiera...','I would like...'],['¿Para tomar?','To drink?'],['Eso es todo','That’s all'],['la cuenta','the check']].map((x,i)=>`<div class="review-item"><span class="num">0${i+1}</span><div class="rtext"><strong>${x[0]}</strong><span>${x[1]}</span></div><button data-say="${x[0]}">▶</button></div>`).join('');document.querySelectorAll('.review-item [data-say]').forEach(b=>b.onclick=()=>{speak(b.dataset.say);mark()})}
function renderRoadmap(){const grid=$('#dayGrid');if(!grid)return;grid.innerHTML=course.map((x,i)=>`<button class="day-card ${i+1===day?'selected':''} ${i+1<day?'done':''}" data-day="${i+1}"><span class="day-number">${String(i+1).padStart(2,'0')}</span><strong>${x[0]}</strong><small>${x[1]}</small></button>`).join('');grid.querySelectorAll('.day-card').forEach(b=>b.onclick=()=>{day=Number(b.dataset.day);completed=0;renderDay();renderProgress();document.querySelector('[data-view="learn"]').click()})}
function addBubble(text,who){const d=document.createElement('div');d.className=`bubble ${who}`;d.innerHTML=`${text}<small>${who==='server'?'SERVIDOR':'TÚ'}</small>`;$('#conversation').appendChild(d);$('#conversation').scrollTop=$('#conversation').scrollHeight}
const prompts=['Buenas tardes. ¿Qué le gustaría?','¿Para tomar?','¿Algo más?','Perfecto. Aquí tiene.'];let step=0;
function startTalk(){ $('#conversation').innerHTML='';step=0;addBubble(prompts[0],'server');speak(prompts[0]) }
function respond(text){const t=text.toLowerCase();if(!t.trim())return;addBubble(text,'user');mark();let reply='';if(step===0){reply=t.includes('quis')||t.includes('quier')?'¡Muy bien! ¿Para tomar?':'Puede decir: “Quisiera los tacos, por favor.” ¿Qué le gustaría?';if(reply.includes('Para'))step=1}else if(step===1){reply='Perfecto. ¿Algo más?';step=2}else if(step===2){reply='Muy bien. Aquí tiene. ¡Que aproveche!';step=3}else{reply='¡Excelente! Has terminado el pedido.';step=0}setTimeout(()=>{addBubble(reply,'server');speak(reply)},300)}
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active-view'));$(`#${t.dataset.view}View`).classList.add('active-view');if(t.dataset.view==='talk'&&!$('#conversation').children.length)startTalk()});
$('#playScene').onclick=()=>{scene.forEach((x,i)=>setTimeout(()=>speak(x.es),i*1600));mark()};$('#playWords').onclick=()=>{phrases.forEach((x,i)=>setTimeout(()=>speak(x[0]),i*1000));mark()};$('#sendBtn').onclick=()=>{const i=$('#replyInput');respond(i.value);i.value=''};$('#replyInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#sendBtn').click()});
let recognition;if('SpeechRecognition'in window||'webkitSpeechRecognition'in window){const R=window.SpeechRecognition||window.webkitSpeechRecognition;recognition=new R();recognition.lang='es-MX';recognition.interimResults=false;recognition.onstart=()=>{$('#micBtn').classList.add('listening');$('#micLabel').textContent='Listening...'};recognition.onend=()=>{$('#micBtn').classList.remove('listening');$('#micLabel').textContent='Start speaking'};recognition.onresult=e=>respond(e.results[0][0].transcript);recognition.onerror=()=>{$('#supportText').textContent='Mic access was unavailable. Type your answer below.'}}else{$('#micBtn').disabled=true;$('#micLabel').textContent='Mic unavailable';$('#supportText').textContent='Use Chrome or Edge for voice input, or type your answer below.'}$('#micBtn').onclick=()=>{if(recognition)recognition.start()};$('#resetBtn').onclick=()=>{completed=0;renderProgress();renderChallenge();startTalk()};$('#resetCourseBtn').onclick=()=>{day=1;completed=0;renderDay();renderProgress();renderChallenge();document.querySelector('[data-view="learn"]').click()};
renderDay();renderScene();renderPhrases();renderChallenge();renderReview();renderProgress();
